name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Run lint (flake8)
      run: flake8 .

    - name: Run tests (pytest)
      run: pytest

    - name: Build Docker image
      run: docker build -t my-fastapi-app .

# Optional: push to Docker Hub if you add secrets DOCKER_USERNAME & DOCKER_PASSWORD
# Uncomment below to enable Docker push

#  docker-push:
#    needs: lint-test-build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Log in to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#
#    - name: Push Docker image
#      run: |
#        docker tag my-fastapi-app ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
#        docker push ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
